<a href="https://colab.research.google.com/github/sbj6364/python-study/blob/main/pandas-basic/17_read_write2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 17번 : read/write panel data(2)

사용하는 코드와 같은 디렉토리 내에 `report.xlsx` 파일이 있을 때, `report.xlsx` 파일의 'report' Sheet 를 불러오는 코드를 작성해보세요.

#### 데이터
[여기](https://future-test-bucket.s3.ap-northeast-2.amazonaws.com/operation/DA001/n17/report.xlsx)를 눌러 데이터(`report.xlsx`)를 다운받아 주세요.

#### 디렉토리 구조
~~~
└── workspace
    └── report.xlsx
    └── solution.py # (or solution.ipynb)

작성중인 코드파일의 이름을 solution 이라고 표기하였습니다.
작성중인 코드파일과 동일한 폴더에 위치하게끔 파일을 옮기세요.
'코드파일과 데이터의 폴더'에 대한 개념도 문제에 포함되어 있습니다.
~~~

In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel('report.xlsx', 'report')
df

    symboling normalized-losses         make  ... width height curb-weight
0           3                 ?  alfa-romero  ...  64.1   48.8        2548
1           3                 ?  alfa-romero  ...  64.1   48.8        2548
2           1                 ?  alfa-romero  ...  65.5   52.4        2823
3           2               164         audi  ...  66.2   54.3        2337
4           2               164         audi  ...  66.4   54.3        2824
..        ...               ...          ...  ...   ...    ...         ...
93          1               103       nissan  ...  63.8   53.5        2024
94          1               128       nissan  ...  63.8   54.5        1951
95          1               128       nissan  ...  63.8   53.3        2028
96          1               122       nissan  ...  63.8   54.5        1971
97          1               103       nissan  ...  63.8   53.5        2037

[98 rows x 14 columns]